<form action='/user/dologin' method="POST">
    <!-- Email input -->
    <div class="form-outline mb-4">
        <input type="email" id="form2Example1" class="form-control" name='mail' />
        <label class="form-label" for="form2Example1">Email address</label>
    </div>

    <!-- Password input -->
    <div class="form-outline mb-4">
        <input type="password" id="form2Example2" class="form-control" name='password' />
        <label class="form-label" for="form2Example2">Password</label>
    </div>

    <!-- Submit button -->
    <input type="submit" class="btn btn-primary btn-block mb-4" value="Sign in">

    <!-- Register buttons -->
    <div class="text-center">
        <p>Not a member? <a href="/user/index">Register</a></p>

    </div>
</form>